import type {
  AppSettings,
  AmbientLayerState,
  AtmosphereState,
  BinauralState,
  ChordState,
  DriftPreset,
  EffectsState,
  MacroState,
  ModulationRoute,
  PersistedState,
  PulseState,
  SaxState,
  JourneyState,
  TuningState,
  VoiceState,
} from '../types';

export const defaultMacros: MacroState = {
  autoMorphEnabled: false,
  autoMorphDepth: 0.62,
  evolution: 0.42,
  stability: 0.68,
  mutation: 0.24,
  speed: 0.32,
  range: 0.38,
  density: 0.72,
  tension: 0.25,
  warmth: 0.68,
  motion: 0.38,
  space: 0.62,
  distortion: 0.12,
  master: 0.36,
};

export const defaultEffects: EffectsState = {
  chorus: 0.22,
  phaser: 0.12,
  flanger: 0.05,
  delay: 0.18,
  delayTime: 1.45,
  delayFeedback: 0.35,
  reverb: 0.48,
  reverbDecay: 14,
  saturation: 0.12,
  bitReduction: 0,
  wobble: 0.08,
  width: 0.72,
  highpass: 24,
  lowpass: 15500,
};

export const defaultAtmosphere: AtmosphereState = {
  enabled: true,
  droneMix: 0.7,
  fieldMix: 0.92,
  rain: 0,
  thunder: 0,
  sonar: 0.06,
  chatter: 0,
  transmission: 0,
  activity: 0.18,
  echo: 0.58,
  distance: 0.72,
  randomness: 0.62,
  speechRate: 0.5,
  speechGlitch: 0.16,
};

export const defaultPulse: PulseState = {
  enabled: false,
  pattern: 'breath',
  tempo: 8,
  depth: 0.34,
  tone: 0.28,
  decay: 0.68,
  irregularity: 0.18,
};

export const defaultBinaural: BinauralState = {
  enabled: false,
  carrier: 140,
  beat: 6,
  level: 0.055,
  drift: 0.08,
};

export const defaultAmbientLayer: AmbientLayerState = {
  enabled: false,
  character: 'aurora',
  level: 0.32,
  activity: 0.34,
  brightness: 0.58,
  decay: 0.72,
  spread: 0.78,
  density: 0.48,
};

export const defaultChord: ChordState = {
  enabled: true,
  running: false,
  key: 0,
  octave: 2,
  waveform: 'sawtooth',
  tempo: 76,
  stepBeats: 4,
  swing: 0.08,
  gate: 0.48,
  level: 0.42,
  detune: 14,
  spread: 0.58,
  cutoff: 2600,
  resonance: 2.4,
  attack: 0.035,
  decay: 0.52,
  sustain: 0.54,
  release: 1.8,
  drive: 0.22,
  steps: [
    { offset: 0, quality: 'minor9', inversion: 0, enabled: true },
    { offset: 8, quality: 'major7', inversion: 1, enabled: true },
    { offset: 3, quality: 'minor7', inversion: 1, enabled: true },
    { offset: 10, quality: 'sus2', inversion: 0, enabled: true },
    { offset: 0, quality: 'minor9', inversion: 1, enabled: true },
    { offset: 8, quality: 'add9', inversion: 0, enabled: true },
    { offset: 5, quality: 'minor7', inversion: 2, enabled: true },
    { offset: 10, quality: 'sus4', inversion: 1, enabled: true },
  ],
};

export const defaultSax: SaxState = {
  enabled: false,
  automatic: false,
  style: 'lonely',
  level: 0.34,
  tone: 0.42,
  breath: 0.38,
  vibrato: 0.46,
  glide: 0.32,
  expression: 0.7,
  activity: 0.24,
  octave: 3,
};

export const defaultJourney: JourneyState = {
  sceneIds: [
    'factory-deep-space',
    'factory-crystal-atmosphere',
    'factory-neon-rain',
    'factory-abyssal-beacon',
  ],
  travelSeconds: 300,
  loop: true,
};

export const defaultTuning: TuningState = {
  root: 36,
  octaveRange: 3,
  mode: 'fifths',
  temperament: 'equal',
  glide: 2.8,
  customRatios: [1, 1.25, 1.5, 2],
};

export const defaultVoices: VoiceState[] = [
  {
    name: 'BEDROCK',
    waveform: 'sine',
    coarse: -12,
    fine: 0,
    detune: 4,
    unison: 2,
    volume: 0.72,
    pan: -0.24,
    cutoff: 960,
    resonance: 0.8,
    filterType: 'lowpass',
    modulation: 0.28,
    sub: 0.34,
    fifth: 0.08,
    octave: 0,
    muted: false,
    solo: false,
    locked: false,
  },
  {
    name: 'FIELD',
    waveform: 'triangle',
    coarse: 0,
    fine: -3,
    detune: 7,
    unison: 2,
    volume: 0.48,
    pan: 0.28,
    cutoff: 2200,
    resonance: 1.2,
    filterType: 'lowpass',
    modulation: 0.4,
    sub: 0,
    fifth: 0.22,
    octave: 0.08,
    muted: false,
    solo: false,
    locked: false,
  },
  {
    name: 'HALO',
    waveform: 'sawtooth',
    coarse: 7,
    fine: 2,
    detune: 11,
    unison: 3,
    volume: 0.23,
    pan: -0.08,
    cutoff: 1400,
    resonance: 2.5,
    filterType: 'bandpass',
    modulation: 0.55,
    sub: 0,
    fifth: 0.15,
    octave: 0.18,
    muted: false,
    solo: false,
    locked: false,
  },
  {
    name: 'DUST',
    waveform: 'noise',
    coarse: 12,
    fine: 0,
    detune: 0,
    unison: 1,
    volume: 0.1,
    pan: 0.12,
    cutoff: 780,
    resonance: 4,
    filterType: 'bandpass',
    modulation: 0.7,
    sub: 0,
    fifth: 0,
    octave: 0,
    muted: false,
    solo: false,
    locked: false,
  },
];

export const defaultModulation: ModulationRoute[] = [
  {
    id: 'pitch-drift',
    source: 'coherent-noise',
    destination: 'pitch',
    rate: 0.16,
    depth: 0.22,
    enabled: true,
  },
  {
    id: 'filter-breath',
    source: 'smooth-random',
    destination: 'cutoff',
    rate: 0.28,
    depth: 0.48,
    enabled: true,
  },
  {
    id: 'field-motion',
    source: 'lfo',
    destination: 'pan',
    rate: 0.22,
    depth: 0.42,
    enabled: true,
  },
  {
    id: 'slow-bloom',
    source: 'long-envelope',
    destination: 'amplitude',
    rate: 0.12,
    depth: 0.2,
    enabled: true,
  },
  {
    id: 'harmonic-weather',
    source: 'random-walk',
    destination: 'harmonics',
    rate: 0.18,
    depth: 0.3,
    enabled: true,
  },
  {
    id: 'room-tide',
    source: 'coherent-noise',
    destination: 'space',
    rate: 0.09,
    depth: 0.18,
    enabled: true,
  },
];

export const defaultSettings: AppSettings = {
  sampleRate: 48000,
  latencyHint: 'balanced',
  defaultMaster: 0.36,
  startMuted: true,
  restoreSession: true,
  closeBehavior: 'quit',
  visualizerQuality: 'medium',
  maximumCpu: false,
  presetLocation: '',
  recordingLocation: '',
  outputDeviceId: '',
};

export function makeDefaultPreset(): DriftPreset {
  const now = new Date().toISOString();
  return {
    id: 'factory-deep-space',
    name: 'Deep Space',
    factory: true,
    favourite: false,
    seed: 'DR-DEEP-SPACE-01',
    macros: structuredClone(defaultMacros),
    voices: structuredClone(defaultVoices),
    effects: structuredClone(defaultEffects),
    atmosphere: structuredClone(defaultAtmosphere),
    pulse: structuredClone(defaultPulse),
    binaural: structuredClone(defaultBinaural),
    ambientLayer: structuredClone(defaultAmbientLayer),
    chord: structuredClone(defaultChord),
    sax: structuredClone(defaultSax),
    tuning: structuredClone(defaultTuning),
    modulation: structuredClone(defaultModulation),
    createdAt: now,
    updatedAt: now,
  };
}

export function makeDefaultState(): PersistedState {
  return {
    version: 1,
    settings: structuredClone(defaultSettings),
    userPresets: [],
    favourites: [],
    lastPresetId: 'factory-deep-space',
    journey: structuredClone(defaultJourney),
  };
}
