import type {
  AmbientLayerState,
  AtmosphereState,
  BinauralState,
  ChordState,
  DriftPreset,
  FilterKind,
  PulseState,
  SaxState,
  TuningMode,
  Waveform,
} from '../types';
import { clamp } from '../audio/math';
import { SeededRandom } from '../audio/seeded';
import { makeDefaultPreset } from './defaults';

interface Character {
  name: string;
  seed: string;
  waveforms: Waveform[];
  mode: TuningMode;
  root: number;
  warmth: number;
  tension: number;
  space: number;
  distortion: number;
  evolution: number;
  density: number;
  cutoff: number;
  reverb: number;
  decay: number;
  noise: number;
  bit: number;
  wobble: number;
  filters?: FilterKind[];
  atmosphere?: Partial<AtmosphereState>;
}

const characters: Character[] = [
  {
    name: 'Deep Space',
    seed: 'DR-DEEP-SPACE-01',
    waveforms: ['sine', 'triangle', 'sawtooth', 'noise'],
    mode: 'fifths',
    root: 33,
    warmth: 0.7,
    tension: 0.2,
    space: 0.86,
    distortion: 0.08,
    evolution: 0.4,
    density: 0.68,
    cutoff: 1400,
    reverb: 0.67,
    decay: 22,
    noise: 0.06,
    bit: 0,
    wobble: 0.05,
    atmosphere: {
      droneMix: 0.62,
      fieldMix: 0.96,
      rain: 0.04,
      thunder: 0.12,
      sonar: 0.48,
      chatter: 0.04,
      transmission: 0.08,
      activity: 0.18,
      echo: 0.86,
      distance: 0.9,
      randomness: 0.68,
      speechRate: 0.46,
      speechGlitch: 0.12,
    },
  },
  {
    name: 'Reactor Hum',
    seed: 'DR-REACTOR-77',
    waveforms: ['square', 'sawtooth', 'triangle', 'noise'],
    mode: 'inharmonic',
    root: 29,
    warmth: 0.32,
    tension: 0.72,
    space: 0.34,
    distortion: 0.4,
    evolution: 0.32,
    density: 0.86,
    cutoff: 820,
    reverb: 0.22,
    decay: 6,
    noise: 0.17,
    bit: 0.12,
    wobble: 0.08,
  },
  {
    name: 'Frozen Broadcast',
    seed: 'DR-FROZEN-19',
    waveforms: ['triangle', 'noise', 'square', 'sine'],
    mode: 'microtonal',
    root: 41,
    warmth: 0.22,
    tension: 0.54,
    space: 0.72,
    distortion: 0.1,
    evolution: 0.27,
    density: 0.44,
    cutoff: 2600,
    reverb: 0.58,
    decay: 17,
    noise: 0.28,
    bit: 0.26,
    wobble: 0.18,
    filters: ['bandpass', 'bandpass', 'highpass', 'bandpass'],
  },
  {
    name: 'Abandoned Station',
    seed: 'DR-STATION-X4',
    waveforms: ['sine', 'triangle', 'noise', 'sawtooth'],
    mode: 'minor',
    root: 31,
    warmth: 0.48,
    tension: 0.42,
    space: 0.76,
    distortion: 0.17,
    evolution: 0.48,
    density: 0.53,
    cutoff: 1700,
    reverb: 0.63,
    decay: 19,
    noise: 0.2,
    bit: 0.08,
    wobble: 0.22,
  },
  {
    name: 'Monolith',
    seed: 'DR-MONOLITH-1',
    waveforms: ['sine', 'square', 'sine', 'triangle'],
    mode: 'octaves' as TuningMode,
    root: 24,
    warmth: 0.66,
    tension: 0.15,
    space: 0.55,
    distortion: 0.26,
    evolution: 0.14,
    density: 0.74,
    cutoff: 640,
    reverb: 0.42,
    decay: 12,
    noise: 0,
    bit: 0,
    wobble: 0.03,
  },
  {
    name: 'Warm Machine',
    seed: 'DR-WARM-808',
    waveforms: ['triangle', 'sine', 'sawtooth', 'triangle'],
    mode: 'major',
    root: 36,
    warmth: 0.92,
    tension: 0.12,
    space: 0.46,
    distortion: 0.22,
    evolution: 0.34,
    density: 0.8,
    cutoff: 2100,
    reverb: 0.36,
    decay: 9,
    noise: 0.02,
    bit: 0,
    wobble: 0.14,
  },
  {
    name: 'Distant Choir',
    seed: 'DR-CHOIR-333',
    waveforms: ['triangle', 'triangle', 'sine', 'sawtooth'],
    mode: 'just',
    root: 38,
    warmth: 0.84,
    tension: 0.22,
    space: 0.91,
    distortion: 0.04,
    evolution: 0.53,
    density: 0.9,
    cutoff: 3200,
    reverb: 0.78,
    decay: 28,
    noise: 0.01,
    bit: 0,
    wobble: 0.09,
  },
  {
    name: 'Subterranean',
    seed: 'DR-SUB-004',
    waveforms: ['sine', 'sine', 'triangle', 'noise'],
    mode: 'phrygian',
    root: 23,
    warmth: 0.78,
    tension: 0.38,
    space: 0.44,
    distortion: 0.18,
    evolution: 0.29,
    density: 0.58,
    cutoff: 540,
    reverb: 0.32,
    decay: 8,
    noise: 0.13,
    bit: 0,
    wobble: 0.05,
  },
  {
    name: 'Endless Engine',
    seed: 'DR-ENGINE-INF',
    waveforms: ['sawtooth', 'square', 'triangle', 'noise'],
    mode: 'fifths',
    root: 28,
    warmth: 0.36,
    tension: 0.45,
    space: 0.38,
    distortion: 0.31,
    evolution: 0.36,
    density: 0.94,
    cutoff: 1250,
    reverb: 0.28,
    decay: 7,
    noise: 0.11,
    bit: 0.06,
    wobble: 0.08,
  },
  {
    name: 'Magnetic Storm',
    seed: 'DR-MAGNET-92',
    waveforms: ['sawtooth', 'noise', 'square', 'triangle'],
    mode: 'whole-tone',
    root: 34,
    warmth: 0.2,
    tension: 0.87,
    space: 0.7,
    distortion: 0.32,
    evolution: 0.78,
    density: 0.82,
    cutoff: 3900,
    reverb: 0.52,
    decay: 14,
    noise: 0.22,
    bit: 0.13,
    wobble: 0.25,
  },
  {
    name: 'Black Ocean',
    seed: 'DR-OCEAN-000',
    waveforms: ['sine', 'triangle', 'noise', 'sine'],
    mode: 'minor',
    root: 26,
    warmth: 0.73,
    tension: 0.31,
    space: 0.88,
    distortion: 0.09,
    evolution: 0.59,
    density: 0.63,
    cutoff: 1050,
    reverb: 0.72,
    decay: 25,
    noise: 0.12,
    bit: 0,
    wobble: 0.16,
  },
  {
    name: 'Numbers Station',
    seed: 'DR-NUMBERS-61',
    waveforms: ['square', 'sine', 'noise', 'triangle'],
    mode: 'chromatic',
    root: 45,
    warmth: 0.28,
    tension: 0.57,
    space: 0.42,
    distortion: 0.13,
    evolution: 0.41,
    density: 0.48,
    cutoff: 2800,
    reverb: 0.31,
    decay: 8,
    noise: 0.24,
    bit: 0.34,
    wobble: 0.12,
    filters: ['bandpass', 'lowpass', 'bandpass', 'highpass'],
    atmosphere: {
      droneMix: 0.58,
      fieldMix: 1,
      rain: 0.04,
      thunder: 0.04,
      sonar: 0.18,
      chatter: 0.68,
      transmission: 0.32,
      activity: 0.46,
      echo: 0.56,
      distance: 0.52,
      randomness: 0.88,
      speechRate: 0.5,
      speechGlitch: 0.5,
    },
  },
  {
    name: 'Broken Tape',
    seed: 'DR-TAPE-WORN',
    waveforms: ['triangle', 'sawtooth', 'sine', 'noise'],
    mode: 'minor',
    root: 39,
    warmth: 0.77,
    tension: 0.33,
    space: 0.54,
    distortion: 0.27,
    evolution: 0.44,
    density: 0.66,
    cutoff: 1850,
    reverb: 0.43,
    decay: 11,
    noise: 0.15,
    bit: 0.18,
    wobble: 0.58,
  },
  {
    name: 'Lunar Dawn',
    seed: 'DR-LUNAR-DAWN',
    waveforms: ['sine', 'triangle', 'triangle', 'sine'],
    mode: 'major',
    root: 40,
    warmth: 0.86,
    tension: 0.08,
    space: 0.82,
    distortion: 0.03,
    evolution: 0.43,
    density: 0.74,
    cutoff: 4100,
    reverb: 0.7,
    decay: 23,
    noise: 0,
    bit: 0,
    wobble: 0.04,
  },
  {
    name: 'Cold Metal',
    seed: 'DR-COLD-FE',
    waveforms: ['sawtooth', 'square', 'triangle', 'noise'],
    mode: 'inharmonic',
    root: 32,
    warmth: 0.08,
    tension: 0.78,
    space: 0.48,
    distortion: 0.38,
    evolution: 0.38,
    density: 0.77,
    cutoff: 5200,
    reverb: 0.39,
    decay: 10,
    noise: 0.16,
    bit: 0.2,
    wobble: 0.06,
    filters: ['bandpass', 'highpass', 'notch', 'bandpass'],
  },
  {
    name: 'Singing Wires',
    seed: 'DR-WIRES-909',
    waveforms: ['sawtooth', 'triangle', 'square', 'sine'],
    mode: 'harmonic',
    root: 43,
    warmth: 0.35,
    tension: 0.51,
    space: 0.62,
    distortion: 0.2,
    evolution: 0.67,
    density: 0.85,
    cutoff: 6200,
    reverb: 0.5,
    decay: 15,
    noise: 0.02,
    bit: 0,
    wobble: 0.2,
  },
  {
    name: 'Dark Matter',
    seed: 'DR-DARK-404',
    waveforms: ['sine', 'square', 'sawtooth', 'noise'],
    mode: 'microtonal',
    root: 21,
    warmth: 0.44,
    tension: 0.69,
    space: 0.94,
    distortion: 0.16,
    evolution: 0.52,
    density: 0.56,
    cutoff: 730,
    reverb: 0.8,
    decay: 32,
    noise: 0.09,
    bit: 0.05,
    wobble: 0.1,
  },
  {
    name: 'Slow Collapse',
    seed: 'DR-COLLAPSE-9',
    waveforms: ['triangle', 'sawtooth', 'noise', 'square'],
    mode: 'phrygian',
    root: 30,
    warmth: 0.39,
    tension: 0.66,
    space: 0.68,
    distortion: 0.35,
    evolution: 0.23,
    density: 0.79,
    cutoff: 1120,
    reverb: 0.55,
    decay: 18,
    noise: 0.18,
    bit: 0.14,
    wobble: 0.31,
  },
  {
    name: 'Cathedral Air',
    seed: 'DR-CATHEDRAL',
    waveforms: ['sine', 'triangle', 'sawtooth', 'noise'],
    mode: 'dorian',
    root: 37,
    warmth: 0.81,
    tension: 0.19,
    space: 0.98,
    distortion: 0.02,
    evolution: 0.35,
    density: 0.69,
    cutoff: 4800,
    reverb: 0.88,
    decay: 38,
    noise: 0.04,
    bit: 0,
    wobble: 0.07,
  },
  {
    name: 'Sleep Signal',
    seed: 'DR-SLEEP-120',
    waveforms: ['sine', 'triangle', 'sine', 'noise'],
    mode: 'just',
    root: 35,
    warmth: 0.96,
    tension: 0.04,
    space: 0.74,
    distortion: 0.01,
    evolution: 0.18,
    density: 0.52,
    cutoff: 1250,
    reverb: 0.64,
    decay: 21,
    noise: 0.03,
    bit: 0,
    wobble: 0.09,
  },
  {
    name: 'Neon Rain',
    seed: 'DR-NEON-2019',
    waveforms: ['sawtooth', 'triangle', 'sine', 'noise'],
    mode: 'minor',
    root: 39,
    warmth: 0.83,
    tension: 0.38,
    space: 0.84,
    distortion: 0.18,
    evolution: 0.31,
    density: 0.83,
    cutoff: 2750,
    reverb: 0.73,
    decay: 21,
    noise: 0.05,
    bit: 0.03,
    wobble: 0.19,
    filters: ['lowpass', 'lowpass', 'bandpass', 'highpass'],
    atmosphere: {
      droneMix: 0.55,
      fieldMix: 1,
      rain: 0.72,
      thunder: 0.22,
      sonar: 0.09,
      chatter: 0.35,
      transmission: 0.58,
      activity: 0.38,
      echo: 0.84,
      distance: 0.72,
      randomness: 0.76,
      speechRate: 0.42,
      speechGlitch: 0.24,
    },
  },
  {
    name: 'Crystal Atmosphere',
    seed: 'DR-CRYSTAL-1977',
    waveforms: ['triangle', 'sawtooth', 'square', 'noise'],
    mode: 'dorian',
    root: 38,
    warmth: 0.78,
    tension: 0.2,
    space: 0.8,
    distortion: 0.08,
    evolution: 0.4,
    density: 0.9,
    cutoff: 3650,
    reverb: 0.68,
    decay: 19,
    noise: 0.16,
    bit: 0,
    wobble: 0.12,
    filters: ['lowpass', 'lowpass', 'bandpass', 'highpass'],
    atmosphere: {
      droneMix: 0.68,
      fieldMix: 0.92,
      rain: 0.08,
      thunder: 0.07,
      sonar: 0.25,
      chatter: 0.06,
      transmission: 0.14,
      activity: 0.2,
      echo: 0.74,
      distance: 0.8,
      randomness: 0.58,
      speechRate: 0.53,
      speechGlitch: 0.08,
    },
  },
  {
    name: 'Off-World Terminal',
    seed: 'DR-TERMINAL-09',
    waveforms: ['sine', 'triangle', 'sawtooth', 'noise'],
    mode: 'minor',
    root: 34,
    warmth: 0.58,
    tension: 0.43,
    space: 0.88,
    distortion: 0.19,
    evolution: 0.36,
    density: 0.7,
    cutoff: 1850,
    reverb: 0.76,
    decay: 24,
    noise: 0.18,
    bit: 0.09,
    wobble: 0.2,
    filters: ['lowpass', 'bandpass', 'lowpass', 'highpass'],
    atmosphere: {
      droneMix: 0.52,
      fieldMix: 1,
      rain: 0.62,
      thunder: 0.22,
      sonar: 0.08,
      chatter: 0.42,
      transmission: 0.58,
      activity: 0.42,
      echo: 0.82,
      distance: 0.68,
      randomness: 0.74,
      speechRate: 0.4,
      speechGlitch: 0.32,
    },
  },
  {
    name: 'Abyssal Beacon',
    seed: 'DR-ABYSS-7000',
    waveforms: ['sine', 'sine', 'triangle', 'noise'],
    mode: 'fifths',
    root: 22,
    warmth: 0.67,
    tension: 0.29,
    space: 0.94,
    distortion: 0.09,
    evolution: 0.29,
    density: 0.55,
    cutoff: 680,
    reverb: 0.82,
    decay: 31,
    noise: 0.08,
    bit: 0,
    wobble: 0.06,
    filters: ['lowpass', 'lowpass', 'bandpass', 'bandpass'],
    atmosphere: {
      droneMix: 0.56,
      fieldMix: 1,
      rain: 0.12,
      thunder: 0.36,
      sonar: 0.72,
      chatter: 0.08,
      transmission: 0.14,
      activity: 0.3,
      echo: 0.88,
      distance: 0.86,
      randomness: 0.52,
      speechRate: 0.36,
      speechGlitch: 0.18,
    },
  },
  {
    name: 'Delta Night',
    seed: 'DR-DELTA-NIGHT-25',
    waveforms: ['sine', 'triangle', 'sine', 'noise'],
    mode: 'just',
    root: 33,
    warmth: 0.94,
    tension: 0.03,
    space: 0.82,
    distortion: 0.01,
    evolution: 0.16,
    density: 0.48,
    cutoff: 980,
    reverb: 0.66,
    decay: 25,
    noise: 0.025,
    bit: 0,
    wobble: 0.035,
    atmosphere: {
      droneMix: 0.66,
      fieldMix: 0.72,
      rain: 0.08,
      thunder: 0.03,
      sonar: 0,
      chatter: 0,
      transmission: 0,
      activity: 0.08,
      echo: 0.7,
      distance: 0.9,
      randomness: 0.38,
      speechRate: 0.5,
      speechGlitch: 0,
    },
  },
  {
    name: 'Theta Passage',
    seed: 'DR-THETA-PASSAGE-6',
    waveforms: ['triangle', 'sine', 'triangle', 'noise'],
    mode: 'dorian',
    root: 38,
    warmth: 0.86,
    tension: 0.08,
    space: 0.9,
    distortion: 0.025,
    evolution: 0.28,
    density: 0.58,
    cutoff: 1750,
    reverb: 0.76,
    decay: 29,
    noise: 0.035,
    bit: 0,
    wobble: 0.07,
  },
  {
    name: 'Alpha Float',
    seed: 'DR-ALPHA-FLOAT-10',
    waveforms: ['sine', 'triangle', 'sawtooth', 'noise'],
    mode: 'major',
    root: 45,
    warmth: 0.78,
    tension: 0.1,
    space: 0.8,
    distortion: 0.035,
    evolution: 0.32,
    density: 0.66,
    cutoff: 2800,
    reverb: 0.66,
    decay: 20,
    noise: 0.025,
    bit: 0,
    wobble: 0.09,
  },
  {
    name: 'Midnight Sax',
    seed: 'DR-MIDNIGHT-SAX-47',
    waveforms: ['triangle', 'sawtooth', 'sine', 'noise'],
    mode: 'minor',
    root: 41,
    warmth: 0.79,
    tension: 0.27,
    space: 0.88,
    distortion: 0.1,
    evolution: 0.3,
    density: 0.62,
    cutoff: 2100,
    reverb: 0.76,
    decay: 25,
    noise: 0.045,
    bit: 0,
    wobble: 0.13,
    atmosphere: {
      droneMix: 0.5,
      fieldMix: 0.84,
      rain: 0.24,
      thunder: 0.04,
      sonar: 0.05,
      chatter: 0.08,
      transmission: 0.06,
      activity: 0.12,
      echo: 0.82,
      distance: 0.86,
      randomness: 0.58,
      speechRate: 0.43,
      speechGlitch: 0.1,
    },
  },
];

const binauralProfiles: Record<string, Partial<BinauralState>> = {
  'Delta Night': {
    enabled: true,
    carrier: 110,
    beat: 2.5,
    level: 0.05,
    drift: 0.04,
  },
  'Theta Passage': {
    enabled: true,
    carrier: 140,
    beat: 6,
    level: 0.052,
    drift: 0.1,
  },
  'Alpha Float': {
    enabled: true,
    carrier: 180,
    beat: 10,
    level: 0.046,
    drift: 0.14,
  },
};

const ambientProfiles: Record<string, Partial<AmbientLayerState>> = {
  'Deep Space': {
    character: 'stars',
    level: 0.24,
    activity: 0.2,
    brightness: 0.42,
    decay: 0.78,
    spread: 0.92,
    density: 0.25,
  },
  'Crystal Atmosphere': {
    character: 'glass',
    level: 0.3,
    activity: 0.38,
    brightness: 0.74,
    decay: 0.82,
    spread: 0.9,
    density: 0.42,
  },
  'Neon Rain': {
    character: 'aurora',
    level: 0.28,
    activity: 0.3,
    brightness: 0.54,
    decay: 0.76,
    spread: 0.82,
    density: 0.48,
  },
  'Delta Night': {
    enabled: true,
    character: 'choir',
    level: 0.19,
    activity: 0.13,
    brightness: 0.24,
    decay: 0.9,
    spread: 0.7,
    density: 0.3,
  },
  'Theta Passage': {
    enabled: true,
    character: 'aurora',
    level: 0.27,
    activity: 0.28,
    brightness: 0.46,
    decay: 0.86,
    spread: 0.84,
    density: 0.5,
  },
  'Alpha Float': {
    enabled: true,
    character: 'glass',
    level: 0.25,
    activity: 0.42,
    brightness: 0.7,
    decay: 0.68,
    spread: 0.88,
    density: 0.38,
  },
  'Midnight Sax': {
    enabled: true,
    character: 'stars',
    level: 0.18,
    activity: 0.16,
    brightness: 0.34,
    decay: 0.84,
    spread: 0.9,
    density: 0.22,
  },
};

const saxProfiles: Record<string, Partial<SaxState>> = {
  'Neon Rain': {
    style: 'noir',
    level: 0.31,
    tone: 0.36,
    breath: 0.42,
    vibrato: 0.5,
    glide: 0.38,
    expression: 0.72,
    activity: 0.2,
    octave: 3,
  },
  'Midnight Sax': {
    enabled: true,
    automatic: true,
    style: 'lonely',
    level: 0.38,
    tone: 0.32,
    breath: 0.46,
    vibrato: 0.58,
    glide: 0.48,
    expression: 0.82,
    activity: 0.28,
    octave: 3,
  },
};

const pulseProfiles: Record<string, Partial<PulseState>> = {
  'Warm Machine': {
    enabled: true,
    pattern: 'heartbeat',
    tempo: 14,
    depth: 0.3,
    tone: 0.24,
    decay: 0.42,
    irregularity: 0.08,
  },
  'Endless Engine': {
    enabled: true,
    pattern: 'drift',
    tempo: 11,
    depth: 0.4,
    tone: 0.34,
    decay: 0.58,
    irregularity: 0.3,
  },
  'Crystal Atmosphere': {
    enabled: true,
    pattern: 'breath',
    tempo: 7,
    depth: 0.25,
    tone: 0.5,
    decay: 0.8,
    irregularity: 0.12,
  },
  'Abyssal Beacon': {
    enabled: true,
    pattern: 'beacon',
    tempo: 5,
    depth: 0.42,
    tone: 0.2,
    decay: 0.88,
    irregularity: 0.2,
  },
};

const chordProfiles: Record<string, Partial<ChordState>> = {
  'Warm Machine': {
    key: 9,
    tempo: 92,
    stepBeats: 2,
    gate: 0.34,
    cutoff: 3400,
    release: 1.2,
    drive: 0.28,
  },
  'Neon Rain': {
    key: 3,
    tempo: 74,
    stepBeats: 4,
    swing: 0.12,
    level: 0.5,
    detune: 18,
    spread: 0.72,
    cutoff: 1900,
    resonance: 3.1,
    attack: 0.07,
    release: 2.6,
    drive: 0.32,
    steps: [
      { offset: 0, quality: 'minor9', inversion: 0, enabled: true },
      { offset: 8, quality: 'major7', inversion: 1, enabled: true },
      { offset: 5, quality: 'minor7', inversion: 2, enabled: true },
      { offset: 10, quality: 'sus2', inversion: 1, enabled: true },
      { offset: 0, quality: 'minor9', inversion: 1, enabled: true },
      { offset: 8, quality: 'add9', inversion: 0, enabled: true },
      { offset: 3, quality: 'major7', inversion: 2, enabled: true },
      { offset: 10, quality: 'sus4', inversion: 1, enabled: true },
    ],
  },
  'Crystal Atmosphere': {
    key: 2,
    tempo: 82,
    stepBeats: 4,
    level: 0.38,
    detune: 11,
    spread: 0.84,
    cutoff: 4200,
    attack: 0.12,
    release: 3.1,
    drive: 0.12,
  },
  'Off-World Terminal': {
    key: 1,
    tempo: 68,
    stepBeats: 4,
    swing: 0.18,
    level: 0.47,
    detune: 22,
    cutoff: 1450,
    resonance: 4.2,
    release: 2.8,
    drive: 0.38,
  },
  'Midnight Sax': {
    key: 5,
    octave: 2,
    tempo: 64,
    stepBeats: 4,
    swing: 0.16,
    gate: 0.58,
    level: 0.4,
    detune: 12,
    spread: 0.68,
    cutoff: 1750,
    resonance: 2.7,
    attack: 0.09,
    release: 3.2,
    drive: 0.2,
    steps: [
      { offset: 0, quality: 'minor9', inversion: 0, enabled: true },
      { offset: 8, quality: 'major7', inversion: 1, enabled: true },
      { offset: 3, quality: 'minor7', inversion: 1, enabled: true },
      { offset: 10, quality: 'sus2', inversion: 0, enabled: true },
      { offset: 5, quality: 'minor7', inversion: 2, enabled: true },
      { offset: 1, quality: 'major7', inversion: 1, enabled: true },
      { offset: 0, quality: 'minor9', inversion: 1, enabled: true },
      { offset: 10, quality: 'sus4', inversion: 1, enabled: true },
    ],
  },
};

function buildPreset(character: Character, index: number): DriftPreset {
  const preset = makeDefaultPreset();
  const random = new SeededRandom(character.seed);
  preset.id = `factory-${character.name.toLowerCase().replace(/\s+/g, '-')}`;
  preset.name = character.name;
  preset.seed = character.seed;
  preset.macros = {
    ...preset.macros,
    warmth: character.warmth,
    tension: character.tension,
    space: character.space,
    distortion: character.distortion,
    evolution: character.evolution,
    density: character.density,
    speed: clamp(0.16 + random.next() * 0.52, 0, 1),
    motion: clamp(0.12 + random.next() * 0.7, 0, 1),
    mutation: clamp(0.12 + character.tension * 0.45, 0, 1),
  };
  preset.tuning.root = character.root;
  preset.tuning.mode = character.mode === ('octaves' as TuningMode) ? 'fifths' : character.mode;
  preset.tuning.glide = 1.4 + random.next() * 5;
  preset.effects = {
    ...preset.effects,
    reverb: character.reverb,
    reverbDecay: character.decay,
    saturation: character.distortion * 0.72,
    bitReduction: character.bit,
    wobble: character.wobble,
    chorus: clamp(0.08 + character.warmth * 0.36, 0, 1),
    phaser: clamp(character.tension * 0.32, 0, 1),
    flanger: clamp(character.tension * 0.18, 0, 1),
    delay: clamp(0.12 + character.space * 0.33, 0, 1),
    delayTime: 0.38 + random.next() * 2.7,
    delayFeedback: 0.19 + character.space * 0.31,
    highpass: character.root < 28 ? 18 : 28,
    lowpass: clamp(character.cutoff * (2.8 + character.warmth * 4), 1800, 18000),
  };
  preset.atmosphere = {
    ...preset.atmosphere,
    ...character.atmosphere,
  };
  preset.pulse = {
    ...preset.pulse,
    ...pulseProfiles[character.name],
  };
  preset.binaural = {
    ...preset.binaural,
    ...binauralProfiles[character.name],
  };
  preset.ambientLayer = {
    ...preset.ambientLayer,
    ...ambientProfiles[character.name],
  };
  preset.chord = {
    ...preset.chord,
    ...chordProfiles[character.name],
  };
  preset.sax = {
    ...preset.sax,
    ...saxProfiles[character.name],
  };
  preset.voices = preset.voices.map((voice, voiceIndex) => ({
    ...voice,
    waveform: character.waveforms[voiceIndex]!,
    coarse: [-12, 0, index % 2 === 0 ? 7 : 5, 12][voiceIndex]!,
    fine: Math.round(random.range(-9, 9)) || 0,
    detune: Math.round(random.range(2, 16) * (0.55 + character.tension)),
    unison:
      voiceIndex === 3 && character.waveforms[voiceIndex] === 'noise'
        ? 1
        : 1 + Math.round(random.range(0, 2)),
    volume:
      voiceIndex === 3
        ? character.noise
        : clamp((0.65 - voiceIndex * 0.14) * (0.65 + character.density * 0.55), 0.08, 0.8),
    pan: clamp(random.signed() * (0.25 + preset.macros.motion * 0.5), -1, 1),
    cutoff: clamp(character.cutoff * (0.72 + voiceIndex * 0.31), 70, 16000),
    resonance: clamp(0.6 + character.tension * 6 + random.next() * 2, 0.1, 14),
    filterType: character.filters?.[voiceIndex] ?? (voiceIndex === 2 ? 'bandpass' : 'lowpass'),
    modulation: clamp(0.18 + random.next() * 0.55, 0, 1),
    sub: voiceIndex === 0 ? clamp(0.15 + character.warmth * 0.32, 0, 0.65) : 0,
    fifth: voiceIndex === 1 ? 0.08 + character.density * 0.24 : voiceIndex === 2 ? 0.1 : 0,
    octave: voiceIndex === 2 ? 0.08 + character.tension * 0.18 : 0,
  }));
  return preset;
}

export const factoryPresets: DriftPreset[] = characters.map(buildPreset);
